# macro for interactive session

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

/process/em/verbose 0
/process/had/verbose 0

/vis/verbose 0

#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4

# Initialize kernel
/run/initialize


# Visualization setting
# /control/execute vis.mac

# Load particle information
/control/execute gps.mac
